### ISSUE TITLE
[Question] Breakdown on 'cde' vs. rocket-chip's 'config' package

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/context-dependent-environments#9]
What's the breakdown on when to use `cde` vs. when to use rocket-chip's `config`? Related to this, is `cde` deprecated in favor of rocket-chip's `config`?

I'm looking at the project-template and fpga-zynq repos and these are both still using `cde` while rocket-chip has been using `config` exclusively for some time. I've made the jump to `config`, but now I'm having issues as the project-template and fpga-zynq both expect to have `cde` available.

In order to make this available am I expected to have done an `sbt publish-local` for `cde`?

**Comment by colinschmidt** [comment]
I think we should move those other repos to ```config``` . I believe they are just languishing due to a lack of time/internal use case.

I'm not familiar with using both ```cde``` and ```config``` in one project.

**Comment by ccelio** [comment]
The update from `cde` to `config` is relatively painless. The only feature lost is "knob", but I don't think anyone has been using it to drive DSE.

**Comment by seldridge** [comment]
@colinschmidt -- Got it. It would be great if these were updated, but I realize I'm to blame for outpacing `fpga-zynq`. There are some branches that pull in newer rocket-chip versions (post `cde` removal), but I'm reluctant to diverge into miscellaneous branches. I'll move this discussion over there.

@ccelio -- Yes, the pain-free nature has been my experience.
